SELECT DISTINCT
	LEFT(CAST(PFUNCAO.CODIGO AS VARCHAR), 8) AS [Código do Cargo],
	LEFT(CAST(PFUNCAO.NOME AS VARCHAR), 40) AS [Descrição do Cargo],
	REPLACE(LEFT(CAST(PFUNCAO.CBO2002 AS VARCHAR), 6),'-','') AS [CBO]
FROM PFUNCAO