SELECT DISTINCT
	LEFT(CAST(PFUNCAO.CODCOLIGADA AS VARCHAR) + CAST(PFUNCAO.CODIGO AS VARCHAR), 8) AS [Código do Cargo],
	LEFT(CAST(PFUNCAO.NOME AS VARCHAR), 40) AS [Descrição do Cargo],
	LEFT(CAST(REPLACE(REPLACE(ISNULL(PFUNCAO.CBO2002, PFUNCAO.CBO),'-',''),' ','') AS VARCHAR), 6) AS [CBO]
FROM PFUNCAO