SELECT
    '' AS [Código da Empresa, cfe. Tabela de Empresas],
    '' AS [Código do Estabelecimento Atual, cfe. Tabela de Estabelecimentos],
    '' AS [Código da Unidade, cfe. Tabela de Unidades],
    '' AS [Código do Contrato],
    '' AS [Código da Pessoa, cfe. Tabela de Pessoas],
    LEFT(CAST(PFUNC.CODSITUACAO AS VARCHAR), 1) AS [Situação],
    FORMAT(PFUNC.DATAADMISSAO, 'ddMMyyyy') AS [Data de Admissão],
    LEFT(CAST(PFUNC.CODRECEBIMENTO AS VARCHAR), 1) AS [Tipo de Salário],
    '' AS [Salário Contratual, cfe. Tipo de Salário],
    '' AS [Horas Contratuais, cfe. Tipo de Salário. Informar Horas/Mês nos contratos de Horistas (Tipo de Salário “5”).],
    '' AS [Percentual de Insalubridade],
    '' AS [Percentual de Periculosidade],
    '' AS [Nível de Exposição a Agente Nocivo],
    RIGHT('000' + LEFT(CAST(PFUNC.CODBANCOPAGTO AS INTEGER), 3), 3) AS [Número do Banco do Funcionário (Banco Central)],
    RIGHT('0000' + LEFT(CAST(PFUNC.CODAGENCIAPAGTO AS INTEGER), 4), 4) AS [Agencia Bancária do Funcionário],
    LEFT(CAST(PFUNC.CODAGENCIAPAGTO AS INTEGER), 1) AS [Dígito da Agência Bancária do Funcionário],
    REPLACE(REPLACE(LEFT(CAST(PFUNC.CONTAPAGAMENTO AS VARCHAR), 15),'-',''),' ','') AS [Número/Dígito da Conta Corrente],
    '' AS [Cadastro do Empregado na CEF (para o FGTS)],
    '' AS [Data de Início do Contrato de Experiência/Temporário],
    '' AS [Data de Término do Contrato de Experiência/Temporário],
    '' AS [Número de Dias do Contrato de Experiência/Temporário],
    '' AS [Data de Início da Prorrogação do Contrato de Experiência],
    '' AS [Data de Término da Prorrogação do Contrato de Experiência],
    '' AS [Número de Dias da Prorrogação do Contrato de Experiência],
    FORMAT(PFUNC.DATADEMISSAO, 'ddMMyyyy') AS [Data da Rescisão],
    '' AS [Código do Cargo, cfe. Tabela de Cargos],
    LEFT(CAST(PFUNC.MATRICULAESOCIAL AS VARCHAR), 30) AS [Matrícula para o eSocial],
    2 AS [Tipo de Contrato],
    '' AS [Motivo de Rescisão Darwin],
    LEFT(CAST(PFUNC.CODCATEGORIAESOCIAL AS VARCHAR), 8) AS [Vínculo Empregatício],
    '' AS [Tipo de Admissão para o eSocial]
FROM PFUNC