SELECT
	LEFT(
		RIGHT('00000000' + (CAST(PFUNC.CODCOLIGADA AS VARCHAR) + CAST(PFUNC.CHAPA AS VARCHAR)), 8), 8
	) AS [Código do Contrato],
	CAST(PFUNC.CODCOLIGADA AS VARCHAR) + CAST(PFUNC.CHAPA AS VARCHAR) AS [Código do Contrato],
	FORMAT(PFUFERIASPER.DATAFIM, 'ddMMyyyy') AS [Data de Término de Gozo das Férias],
	FORMAT(PFUFERIAS.INICIOPERAQUIS, 'ddMMyyyy') AS [Data de Início do Período Aquisitivo],
	FORMAT(PFUFERIASPER.DATAINICIO, 'ddMMyyyy') AS [Data de Início de Gozo das Férias],
	FORMAT(PFUFERIAS.FIMPERAQUIS, 'ddMMyyyy') AS [Data de Término do Período Aquisitivo],
	LEFT(CAST(PFUFERIASPER.NRODIASFERIAS AS DECIMAL(10,2)), 4) AS [Dias de Férias Cedidos],
	LEFT(CAST(PFUFERIASPER.NRODIASABONO AS DECIMAL(10,2)), 4) AS [Dias de Abono Cedidos]
FROM PFUFERIASPER
LEFT JOIN PFUFERIAS
  ON PFUFERIAS.CODCOLIGADA		= PFUFERIASPER.CODCOLIGADA
  AND PFUFERIAS.CHAPA			= PFUFERIASPER.CHAPA
  AND PFUFERIAS.FIMPERAQUIS		= PFUFERIASPER.FIMPERAQUIS
LEFT JOIN PFUNC
  ON PFUNC.CODCOLIGADA			= PFUFERIAS.CODCOLIGADA
  AND PFUNC.CHAPA				= PFUFERIAS.CHAPA
