SELECT
	CASE
		WHEN PFUNC.CODCOLIGADA <> 1 
		THEN RIGHT('00' + CAST(PFUNC.CODCOLIGADA AS VARCHAR), 2) + RIGHT('00' + CAST(PFUNC.CODFILIAL AS VARCHAR), 2) 
		ELSE RIGHT('0000' + CAST(PFUNC.CODFILIAL AS VARCHAR), 4)
	END AS [Código da Unidade, cfe. Tabela de Unidades],
	CAST(PFUNC.CODCOLIGADA AS VARCHAR) + RIGHT(PFUNC.CHAPA, 8 - LEN(CAST(PFUNC.CODCOLIGADA AS VARCHAR))) AS [Código do Contrato],
	FORMAT(PFUFERIASPER.DATAFIM, 'dd/MM/yyyy') AS [Data de Término de Gozo das Férias],
	FORMAT(PFUFERIAS.INICIOPERAQUIS, 'dd/MM/yyyy') AS [Data de Início do Período Aquisitivo],
	FORMAT(PFUFERIASPER.DATAINICIO, 'dd/MM/yyyy') AS [Data de Início de Gozo das Férias],
	FORMAT(PFUFERIAS.FIMPERAQUIS, 'dd/MM/yyyy') AS [Data de Término do Período Aquisitivo],
	LEFT(CAST(PFUFERIASPER.NRODIASFERIAS AS DECIMAL(10,2)), 4) AS [Dias de Férias Cedidos],
	LEFT(CAST(PFUFERIASPER.NRODIASABONO AS DECIMAL(10,2)), 4) AS [Dias de Abono Cedidos]
FROM PFUFERIASPER
LEFT JOIN PFUFERIAS
  ON PFUFERIAS.CODCOLIGADA		= PFUFERIASPER.CODCOLIGADA
  AND PFUFERIAS.CHAPA			= PFUFERIASPER.CHAPA
  AND PFUFERIAS.FIMPERAQUIS		= PFUFERIASPER.FIMPERAQUIS
LEFT JOIN PFUNC
  ON PFUNC.CODCOLIGADA			= PFUFERIAS.CODCOLIGADA
  AND PFUNC.CHAPA				= PFUFERIAS.CHAPA