WITH CTE AS
(
	SELECT
	    CODCOLIGADA,
	    CHAPA,
	    DTMUDANCA,
	    CODSECAO,
	    LEAD(CODSECAO) OVER (
	        PARTITION BY CODCOLIGADA, CHAPA
	        ORDER BY DTMUDANCA
	    ) AS PROXIMA_SECAO
	FROM PFHSTSEC
	WHERE LEN(CODSECAO) > 2
),
DADOS AS (
  SELECT
  	CODCOLIGADA,
    CASE
        WHEN CODCOLIGADA <> 1 
        THEN RIGHT('00' + CAST(CODCOLIGADA AS VARCHAR), 2) + RIGHT('00' + CAST(REPLACE(LEFT(CODSECAO, 2), '.','') AS VARCHAR), 2) 
        ELSE RIGHT('0000' + CAST(REPLACE(LEFT(CODSECAO, 2), '.','') AS VARCHAR), 4)
    END AS UNIDADE, 
    CAST(CODCOLIGADA AS VARCHAR) + RIGHT(CHAPA, 8 - LEN(CAST(CODCOLIGADA AS VARCHAR))) AS CONTRATO,
    FORMAT(DTMUDANCA, 'dd/MM/yyyy') AS DTTRANSF,
    CASE
      WHEN CODCOLIGADA <> 1
      THEN RIGHT('00' + CAST(CODCOLIGADA AS VARCHAR), 2) + RIGHT('00' + CAST(REPLACE(LEFT(CODSECAO, 2), '.','') AS VARCHAR), 2) 
      ELSE RIGHT('0000' + CAST(REPLACE(LEFT(CODSECAO, 2), '.','') AS VARCHAR), 4)
    END AS ORIGEM,
    CASE
      WHEN CODCOLIGADA <> 1
      THEN RIGHT('00' + CAST(CODCOLIGADA AS VARCHAR), 2) + RIGHT('00' + CAST(REPLACE(LEFT(PROXIMA_SECAO, 2), '.','') AS VARCHAR), 2)
      ELSE RIGHT('0000' + CAST(REPLACE(LEFT(PROXIMA_SECAO, 2), '.','') AS VARCHAR), 4)
    END AS DESTINO
  FROM CTE
),
DADOS2 AS (
	SELECT *
	FROM DADOS
	WHERE ORIGEM <> DESTINO
),
DADOS3 AS (
	SELECT
		*,
		ROW_NUMBER() OVER(
			PARTITION BY CONTRATO
			ORDER BY CODCOLIGADA,
					 DTTRANSF
		) AS ORDEM
	FROM DADOS2
)
SELECT
	  UNID_ATUAL.DESTINO   AS [Unidade],
	  DADOS3.CONTRATO      AS [Contrato],
	  DADOS3.DTTRANSF      AS [Dt.Transferência],
	  DADOS3.ORIGEM        AS [Estabelecimento Origem],
	  DADOS3.DESTINO       AS [Estabelecimento Destino]
FROM DADOS3
LEFT JOIN (
	SELECT DISTINCT
		DESTINO,
		CONTRATO
	FROM DADOS3
	WHERE ORDEM = 1
) UNID_ATUAL
  ON UNID_ATUAL.CONTRATO = DADOS3.CONTRATO