WITH CTE AS
(
    SELECT
        CODCOLIGADA,
        CHAPA,
        DTMUDANCA,
        CODSECAO,
        LEAD(CODSECAO) OVER (
            PARTITION BY CODCOLIGADA, CHAPA
            ORDER BY DTMUDANCA
        ) AS PROXIMA_SECAO
    FROM PFHSTSEC
),
TB_UNIDADE AS (
	SELECT
		RIGHT('0000' + CAST(ROW_NUMBER() OVER(ORDER BY CODIGO) AS VARCHAR), 4) AS CODSEQ,
		SECAO.*
	FROM (
	SELECT DISTINCT
		CAST(CODCOLIGADA AS VARCHAR) + CAST(REPLACE(CODIGO,'.','') AS VARCHAR) AS CODIGO,
		DESCRICAO
	FROM PSECAO
	) SECAO
)

SELECT
    TB_UNIDADE.CODSEQ AS [Código da Unidade, cfe. Tabela de Unidades],
    CAST(PFUNC.CODCOLIGADA AS VARCHAR) + RIGHT(PFUNC.CHAPA, 8 - LEN(CAST(PFUNC.CODCOLIGADA AS VARCHAR))) AS [Código do Contrato],
    FORMAT(CTE.DTMUDANCA, 'dd/MM/yyyy') AS [Data da Transferência],
    (
      SELECT TOP 1 CODSEQ FROM TB_UNIDADE WHERE CODIGO = CAST(CTE.CODCOLIGADA AS VARCHAR) + CAST(REPLACE(CTE.CODSECAO,'.','') AS VARCHAR)
    ) AS [Código do Estabelecimento Origem, cfe. Tabela de Estabelecimentos],
    (
      SELECT TOP 1 CODSEQ FROM TB_UNIDADE WHERE CODIGO = CAST(CTE.CODCOLIGADA AS VARCHAR) + CAST(REPLACE(CTE.PROXIMA_SECAO,'.','') AS VARCHAR)
    ) AS [Código do Estabelecimento Destino, cfe. Tabela de Estabelecimentos]
FROM CTE
LEFT JOIN PFUNC
  ON PFUNC.CODCOLIGADA              = CTE.CODCOLIGADA
  AND PFUNC.CHAPA                   = CTE.CHAPA
LEFT JOIN TB_UNIDADE
  ON TB_UNIDADE.CODIGO			= CAST(PFUNC.CODCOLIGADA AS VARCHAR) + CAST(REPLACE(PFUNC.CODSECAO,'.','') AS VARCHAR)
WHERE CTE.PROXIMA_SECAO IS NOT NULL
  AND CTE.CODSECAO <> CTE.PROXIMA_SECAO;