WITH CTE AS
(
    SELECT
        CODCOLIGADA,
        CHAPA,
        DTMUDANCA,
        CODSECAO,
        LEAD(CODSECAO) OVER (
            PARTITION BY CODCOLIGADA, CHAPA
            ORDER BY DTMUDANCA
        ) AS PROXIMA_SECAO
    FROM PFHSTSEC
)

SELECT
    RIGHT('00' + CAST(PFUNC.CODCOLIGADA AS VARCHAR), 2) + RIGHT('00' + CAST(PFUNC.CODFILIAL AS VARCHAR), 2) AS [Código da Unidade, cfe. Tabela de Unidades],
    CAST(PFUNC.CODCOLIGADA AS VARCHAR) + RIGHT(PFUNC.CHAPA, 8 - LEN(CAST(PFUNC.CODCOLIGADA AS VARCHAR))) AS [Código do Contrato],
    FORMAT(CTE.DTMUDANCA, 'dd/MM/yyyy') AS [Data da Transferência],
    (
      SELECT TOP 1 CODSEQ FROM TB_UNIDADE WHERE CODIGO = CAST(CTE.CODCOLIGADA AS VARCHAR) + CAST(REPLACE(CTE.CODSECAO,'.','') AS VARCHAR)
    ) AS [Código do Estabelecimento Origem, cfe. Tabela de Estabelecimentos],
    (
      SELECT TOP 1 CODSEQ FROM TB_UNIDADE WHERE CODIGO = CAST(CTE.CODCOLIGADA AS VARCHAR) + CAST(REPLACE(CTE.PROXIMA_SECAO,'.','') AS VARCHAR)
    ) AS [Código do Estabelecimento Destino, cfe. Tabela de Estabelecimentos]
FROM CTE
LEFT JOIN PFUNC
  ON PFUNC.CODCOLIGADA              = CTE.CODCOLIGADA
  AND PFUNC.CHAPA                   = CTE.CHAPA
WHERE CTE.PROXIMA_SECAO IS NOT NULL
  AND CTE.CODSECAO <> CTE.PROXIMA_SECAO;